name: Template rename

on:
  workflow_dispatch:

permissions: write-all

jobs:
  get-context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  rename:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git
        uses: kota65535/github-git-config-action@main
        with:
          user.name: github-actions[bot]
          user.email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Rename project
        uses: kota65535/github-template-rename-action@main
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          from-name: <YOUR TOOL>
          to-name: test
